<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Attribute extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $attributes = [
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 1,
            ],
            [
                'name_en' => 'Is land sorted',
                'name_ar' => 'هل الأرض مصنفة',
                'name_fr' => 'Le terrain est-il trié',
                'category_id' => 2,
            ],
            [
                'name_en' => 'Have maps',
                'name_ar' => 'هل لديك خرائط',
                'name_fr' => 'Avez-vous des cartes',
                'category_id' => 2,
            ],
            [
                'name_en' => 'Number of streets',
                'name_ar' => 'عدد الشوارع',
                'name_fr' => 'Nombre de rues',
                'category_id' => 2,
            ],
            [
                'name_en' => 'Payment system',
                'name_ar' => 'نظام الدفع',
                'name_fr' => 'Système de paiement',
                'category_id' => 2,
            ],
            [
                'name_en' => 'Furnishing',
                'name_ar' => 'الفرش',
                'name_fr' => 'Ameublement',
                'category_id' => 3,
            ],
            [
                'name_en' => 'Levels',
                'name_ar' => 'المستويات',
                'name_fr' => 'Niveaux',
                'category_id' => 3,
            ],
            [
                'name_en' => 'Bathrooms',
                'name_ar' => 'الحمامات',
                'name_fr' => 'Salles de bains',
                'category_id' => 3,
            ],
            [
                'name_en' => 'Finishing',
                'name_ar' => 'التشطيب',
                'name_fr' => 'Finition',
                'category_id' => 3,
            ],
            [
                'name_en' => 'Property Type',
                'name_ar' => 'نوع العقار',
                'name_fr' => 'Type de propriété',
                'category_id' => 3,
            ],
            [
                'name_en' => 'Car Type',
                'name_ar' => 'نوع السيارة',
                'name_fr' => 'Type de voiture',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Gear Type',
                'name_ar' => 'نوع الجير',
                'name_fr' => 'Type de transmission',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Color',
                'name_ar' => 'اللون',
                'name_fr' => 'Couleur',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Number of Cylinders',
                'name_ar' => 'عدد الأسطوانات',
                'name_fr' => 'Nombre de cylindres',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Fuel Type',
                'name_ar' => 'نوع الوقود',
                'name_fr' => 'Type de carburant',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Engine Capacity',
                'name_ar' => 'سعة المحرك',
                'name_fr' => 'Capacité du moteur',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'حالة السلعة',
                'name_fr' => 'État',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Guarantee',
                'name_ar' => 'الضمان',
                'name_fr' => 'Garantie',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Manufacture year',
                'name_ar' => 'سنة التصنيع',
                'name_fr' => 'Année de fabrication',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Kilometers',
                'name_ar' => 'الكيلومترات',
                'name_fr' => 'Kilomètres',
                'category_id' => 4,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'حالة السلعة',
                'name_fr' => 'État',
                'category_id' => 6,
            ],
            [
                'name_en' => 'Gear',
                'name_ar' => 'الجير',
                'name_fr' => 'Boîte de vitesses',
                'category_id' => 6,
            ],
            [
                'name_en' => 'Engine Size',
                'name_ar' => 'حجم المحرك',
                'name_fr' => 'Taille du moteur',
                'category_id' => 6,
            ],
            [
                'name_en' => 'Engine power',
                'name_ar' => 'قوة المحرك',
                'name_fr' => 'Puissance du moteur',
                'category_id' => 6,
            ],
            [
                'name_en' => 'Manufacture year',
                'name_ar' => 'سنة التصنيع',
                'name_fr' => 'Année de fabrication',
                'category_id' => 6,
            ],
            [
                'name_en' => 'Kilometers',
                'name_ar' => 'الكيلومترات',
                'name_fr' => 'Kilomètres',
                'category_id' => 6,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'حالة السلعة',
                'name_fr' => 'État',
                'category_id' => 7,
            ],
            [
                'name_en' => 'Quality',
                'name_ar' => 'جودة السلعة',
                'name_fr' => 'Qualité',
                'category_id' => 7,
            ],
            [
                'name_en' => 'Country of origin',
                'name_ar' => 'بلد المنشأ',
                'name_fr' => 'Pays d\'origine',
                'category_id' => 7,
            ],
            [
                'name_en' => 'Manufacturers',
                'name_ar' => 'الشركات المصنعة',
                'name_fr' => 'Fabricants',
                'category_id' => 7,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'حالة السلعة',
                'name_fr' => 'État',
                'category_id' => 8,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 9,
            ],
            [
                'name_en' => 'Manufacture year',
                'name_ar' => 'سنة التصنيع',
                'name_fr' => 'Année de fabrication',
                'category_id' => 9,
            ],
            [
                'name_en' => 'Unit Type',
                'name_ar' => 'نوع الوحدة',
                'name_fr' => 'Type d\'unité',
                'category_id' => 11,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 11,
            ],
            [
                'name_en' => 'Guarantee',
                'name_ar' => 'الضمان',
                'name_fr' => 'Garantie',
                'category_id' => 11,
            ],
            [
                'name_en' => 'Investment',
                'name_ar' => 'الاستثمار',
                'name_fr' => 'Investissement',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Payment',
                'name_ar' => 'الدفع',
                'name_fr' => 'Paiement',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Available Visa',
                'name_ar' => 'التأشيرة المتاحة',
                'name_fr' => 'Visa disponible',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Rent/M',
                'name_ar' => 'الإيجار/شهر',
                'name_fr' => 'Loyer/mois',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Salaries/M',
                'name_ar' => 'الرواتب/شهر',
                'name_fr' => 'Salaires/mois',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Income/M',
                'name_ar' => 'الدخل/شهر',
                'name_fr' => 'Revenu/mois',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Profit/M',
                'name_ar' => 'الربح/شهر',
                'name_fr' => 'Profit/mois',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Area (M2)',
                'name_ar' => 'المساحة (م2)',
                'name_fr' => 'Surface (m2)',
                'category_id' => 20,
            ],
            [
                'name_en' => 'Gender',
                'name_ar' => 'الجنس',
                'name_fr' => 'Genre',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Nationality',
                'name_ar' => 'الجنسية',
                'name_fr' => 'Nationalité',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Qualification',
                'name_ar' => 'المؤهل',
                'name_fr' => 'Qualification',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Experience Years',
                'name_ar' => 'سنوات الخبرة',
                'name_fr' => 'Années d\'expérience',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Expected Salary',
                'name_ar' => 'الراتب المتوقع',
                'name_fr' => 'Salaire attendu',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Career Level',
                'name_ar' => 'مستوى الوظيفة',
                'name_fr' => 'Niveau de carrière',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Driver License',
                'name_ar' => 'رخصة القيادة',
                'name_fr' => 'Permis de conduire',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Job Type',
                'name_ar' => 'نوع الوظيفة',
                'name_fr' => 'Type d\'emploi',
                'category_id' => 23,
            ],
            [
                'name_en' => 'Gender',
                'name_ar' => 'الجنس',
                'name_fr' => 'Genre',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Nationality',
                'name_ar' => 'الجنسية',
                'name_fr' => 'Nationalité',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Qualification',
                'name_ar' => 'المؤهل',
                'name_fr' => 'Qualification',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Experience Years',
                'name_ar' => 'سنوات الخبرة',
                'name_fr' => 'Années d\'expérience',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Expected Salary',
                'name_ar' => 'الراتب المتوقع',
                'name_fr' => 'Salaire attendu',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Career Level',
                'name_ar' => 'مستوى الوظيفة',
                'name_fr' => 'Niveau de carrière',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Driver License',
                'name_ar' => 'رخصة القيادة',
                'name_fr' => 'Permis de conduire',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Job Type',
                'name_ar' => 'نوع الوظيفة',
                'name_fr' => 'Type d\'emploi',
                'category_id' => 24,
            ],
            [
                'name_en' => 'Delivery Cost',
                'name_ar' => 'تكلفة التوصيل',
                'name_fr' => 'Coût de livraison',
                'category_id' => 29,
            ],
            [
                'name_en' => 'Time of Request',
                'name_ar' => 'وقت الطلب',
                'name_fr' => 'Heure de la demande',
                'category_id' => 29,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 30,
            ],
            [
                'name_en' => 'Guarantee',
                'name_ar' => 'الضمان',
                'name_fr' => 'Garantie',
                'category_id' => 30,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 31,
            ],
            [
                'name_en' => 'SIM Type',
                'name_ar' => 'نوع الشريحة',
                'name_fr' => 'Type de carte SIM',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Storage Capacity',
                'name_ar' => 'سعة التخزين',
                'name_fr' => 'Capacité de stockage',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Camera Resolution',
                'name_ar' => 'دقة الكاميرا',
                'name_fr' => 'Résolution de la caméra',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Guarantee',
                'name_ar' => 'الضمان',
                'name_fr' => 'Garantie',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Operating System',
                'name_ar' => 'نظام التشغيل',
                'name_fr' => 'Système d\'exploitation',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Mobile RAM',
                'name_ar' => 'ذاكرة الوصول العشوائي للهاتف المحمول',
                'name_fr' => 'RAM mobile',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Mobile Screen Size',
                'name_ar' => 'حجم شاشة الهاتف المحمول',
                'name_fr' => 'Taille de l\'écran mobile',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Battery Capacity',
                'name_ar' => 'سعة البطارية',
                'name_fr' => 'Capacité de la batterie',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Secondary',
                'name_ar' => 'ثانوي',
                'name_fr' => 'Secondaire',
                'category_id' => 31,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 32,
            ],
            [
                'name_en' => 'Guarantee',
                'name_ar' => 'الضمان',
                'name_fr' => 'Garantie',
                'category_id' => 32,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 33,
            ],
            [
                'name_en' => 'Mega Pixel',
                'name_ar' => 'ميجا بيكسل',
                'name_fr' => 'Méga Pixel',
                'category_id' => 33,
            ],
            [
                'name_en' => 'Optical Zoom',
                'name_ar' => 'تكبير بصري',
                'name_fr' => 'Zoom optique',
                'category_id' => 33,
            ],
            [
                'name_en' => 'Wifi Support',
                'name_ar' => 'دعم الواي فاي',
                'name_fr' => 'Prise en charge du Wifi',
                'category_id' => 33,
            ],
            [
                'name_en' => 'Bluetooth',
                'name_ar' => 'بلوتوث',
                'name_fr' => 'Bluetooth',
                'category_id' => 33,
            ],
            [
                'name_en' => 'Guarantee',
                'name_ar' => 'الضمان',
                'name_fr' => 'Garantie',
                'category_id' => 33,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 35,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 37,
            ],
            [
                'name_en' => 'Count of Wheels',
                'name_ar' => 'عدد العجلات',
                'name_fr' => 'Nombre de roues',
                'category_id' => 37,
            ],
            [
                'name_en' => 'Bluetooth',
                'name_ar' => 'بلوتوث',
                'name_fr' => 'Bluetooth',
                'category_id' => 37,
            ],
            [
                'name_en' => 'Charging Period',
                'name_ar' => 'فترة الشحن',
                'name_fr' => 'Période de charge',
                'category_id' => 37,
            ],
            [
                'name_en' => 'Guarantee',
                'name_ar' => 'ضمان',
                'name_fr' => 'Garantie',
                'category_id' => 37,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 39,
            ],
            [
                'name_en' => 'Age',
                'name_ar' => 'العمر',
                'name_fr' => 'Âge',
                'category_id' => 40,
            ],
            [
                'name_en' => 'Age',
                'name_ar' => 'العمر',
                'name_fr' => 'Âge',
                'category_id' => 41,
            ],
            [
                'name_en' => 'Age',
                'name_ar' => 'العمر',
                'name_fr' => 'Âge',
                'category_id' => 42,
            ],
            [
                'name_en' => 'Sex',
                'name_ar' => 'الجنس',
                'name_fr' => 'Sexe',
                'category_id' => 42,
            ],
            [
                'name_en' => 'Material',
                'name_ar' => 'المادة',
                'name_fr' => 'Matériau',
                'category_id' => 45,
            ],
            [
                'name_en' => 'Pattern',
                'name_ar' => 'النمط',
                'name_fr' => 'Motif',
                'category_id' => 45,
            ],
            [
                'name_en' => 'Scarcity',
                'name_ar' => 'الندرة',
                'name_fr' => 'Rareté',
                'category_id' => 45,
            ],
            [
                'name_en' => 'Condition',
                'name_ar' => 'الحالة',
                'name_fr' => 'État',
                'category_id' => 45,
            ],
            [
                'name_en' => 'Production Year',
                'name_ar' => 'سنة الإنتاج',
                'name_fr' => 'Année de production',
                'category_id' => 45,
            ],
        ];
        DB::table('attributes')->insert($attributes);
    }
}
